# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 智慧计算与优化实验室
description: > # this means to ignore newlines until "baseurl:"
  这里请填写实验室简介。可以在根目录下的  _config.yml 文件中修改。这里的内容会被搜索引擎索引。

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://smart.hust.edu.cn" # the base hostname & protocol for your site
github_username:  HUST-Smart

# Build settings
markdown: kramdown
